### ISSUE TITLE
Add Social Card to all Blogs

### ISSUE THREAD

**Issue by himanshu-03** [tcet-opensource/documentation#108]
This is an open issue and anyone internally or externally can contribute to this issue.
We need all blogs in the website to have a social card where one can click and redirect themselves to the blog.

For example;: 

![image](https://github.com/tcet-opensource/documentation/assets/97957777/235469ee-efb6-4c44-a79b-e18f9a0cdfea)

Docusaurus themselves are using this approach to showcase all their blogs.

So if anyone wants to contribute to this issue you can mention it down here in the comments section.

**Comment by vish-rt** [comment]
Issue Revision - August 27th 2023

Currently whenever a user opens the blogs page of the website, they are bombarded with all blogs open at the same time. This makes the user having to either deliberately scroll through all blogs to find the one they're interested in reading, or be smart and use the dedicated sidebar.

However a good blog page usually encompasses the following:
- A neat title
- A short summary of the blog (usually the first paragraph)
- A really fancy image
- A "Read more" tag to further read the blog in detail

To reduce the clutter on the blogs page and to overall have it look more appealing, we should opt to have a similar structure, which is seen in Docusaurus' own blog. To do so, the following tasks need to be completed:

- [ ] Convert all current blogs to `.mdx` format for the use of certain important HTML tags (this is required to be done in a later issue. This issue shall mainly focus on making changes to the configurations)
- [ ] Add `<!--truncate--> to all `index.mdx` files, wherever applicable (to be done in a later issue)
- [ ] Add a restriction to the amount of blogs visible on the main blogs page (reflect newer blogs on the main blogs page)
- [ ] Add a way for the config to understand truncate statements to bypass compilation errors.
