### ISSUE TITLE
[UI] Micro Changes

### ISSUE THREAD

**Issue by JayeshVP24** [tcet-opensource/documentation#112]
- [ ] In developed projects, the right panel, make the active project card brighter
- [ ] In underdeveloped projects, left align all text
- [ ] Change padding of each component to 1.25rem for mobile i.e p-5 and 4rem for desktop i.e p-16. Except underdevelopment projects, make sure all other components have same padding. In underdevelopment projects, add this padding to only the heading.
- [ ] Change the gradient of each component in teams section. Check the new gradient in figma. Copy that.

**Comment by himanshu-03** [comment]
Closed in #120
