### ISSUE TITLE
[TOS] - Updating About Organization Page

### ISSUE THREAD

**Issue by himanshu-03** [tcet-opensource/documentation#202]
The [About Organizaion Page](https://opensource.tcetmumbai.in/docs/about-tcetopensource) of TCET Open Source website needs to be changed!

Page Link: https://opensource.tcetmumbai.in/docs/about-tcetopensource

Following are the changes which are to be made:

- Description about TCET Open Source needs to be changed
- Teams Section needs to be update according to the new organization structure
- Live, Ongoing, and Upcoming Projects details and representation should be clear and visually appealing.

![image](https://github.com/tcet-opensource/documentation/assets/97957777/07c7c2f3-c812-49fa-80d6-5de8900248d8)

**Comment by AadilRayeen** [comment]
can i work on this issue ??

**Comment by himanshu-03** [comment]
> can i work on this issue ??

Yes you can start working on this issue. Create a branch with issue name and problem to be fixed.
Best of luck!
