### ISSUE TITLE
[FIX] URL for TCET LINUX Website About page

### ISSUE THREAD

**Issue by AadilRayeen** [tcet-opensource/documentation#208]
- Change the incorrect url from (https://tcet-linux-website/) to (https://linux.tcetmumbai.in/), that has been mentioned on the About  page of TCET LINUX Website docs.

**Comment by Akash6222** [comment]
![2023-09-02T10:53:17,379258755+05:30](https://github.com/tcet-opensource/documentation/assets/101584901/f9f478cc-2743-4d72-8990-75b37ccf8329)

**Comment by Akash6222** [comment]
In the above image change the TCET Linux website link to https://linux.tcetmumbai.in/
