### ISSUE TITLE
[TL] System Maintenance

### ISSUE THREAD

**Issue by MJ665** [tcet-opensource/documentation#239]
### Describe the improvement

Add content in system-maintenance.md

### Why do we need this?

This will help guide user for system maintainance

### Do you have a proposed solution?

-

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu-03** [comment]
Fixed in #273
