### ISSUE TITLE
[TL] Resources

### ISSUE THREAD

**Issue by MJ665** [tcet-opensource/documentation#242]
### Describe the improvement

Add content in resources.md

### Why do we need this?

This will contain list of resources used for developing TCET Linux

### Do you have a proposed solution?

-

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu-03** [comment]
Done

**Comment by MJ665** [comment]
@saashaspace Complete This Issue add the content in resource md file

**Comment by MJ665** [comment]
https://github.com/tcet-opensource/documentation/pull/329

Done
