### ISSUE TITLE
[BUG] - Footer Alignment

### ISSUE THREAD

**Issue by kamalika0363** [tcet-opensource/documentation#263]
### Describe the bug

![image](https://github.com/tcet-opensource/documentation/assets/59131714/5874a269-8483-4b96-a989-b63fcb86fbd1)
Alignment of footer in small screen is not in center.

### Actual behavior

Footer alignment is aligned towards a little left.

### Expected behavior

Footer alignment should be in the center.

### How to Reproduce?

Browser Inspect

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by akssshh** [comment]
Can i work on this?

**Comment by Aastha-S-Rai** [comment]
i would like to work on this

**Comment by 06Vikrant** [comment]
could you assign me to work on this issue

**Comment by 06Vikrant** [comment]
I would like to work on this issue

**Comment by kamalika0363** [comment]
@06Vikrant part of this issue is solved, you may go ahead and create an separate issue. 
You can work on that.
For now I'm closing this issue.
