### ISSUE TITLE
[FEATURE] - Adding Discord Handle

### ISSUE THREAD

**Issue by Mahitej28** [tcet-opensource/documentation#283]
### Describe the improvement

I would like to contribute to this repository by adding, Discord handle in the `Social media section`.

### Why do we need this?

Tcet Open Source's important platform for people to connect is Discord, so it should be present on the website for easy access.

### Do you have a proposed solution?

Adding discord icon with a valid link.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu-03** [comment]
Fixed in #287
