### ISSUE TITLE
[FEATURE] - Make the action dynamic by adding scroll feature while navigating to a section by clicking on NavBar 

### ISSUE THREAD

**Issue by cryptic-pr03** [tcet-opensource/documentation#286]
### Describe the improvement

![image](https://github.com/tcet-opensource/documentation/assets/92126782/3448deb2-c5ad-4769-9ab9-79ba4764059a)
Clicking any link on navigation bar takes the user to that section instantly. e.g. on clicking Cooking Project
![image](https://github.com/tcet-opensource/documentation/assets/92126782/d1dd8894-4c2d-4db9-b657-689e5f420f4b)

 

### Why do we need this?

- Adding the scrolling style is will be in sync with the natural dynamic flow of the page. 
- It will also make the webpage more user-friendly.

### Do you have a proposed solution?

- Adding css property should fix the issue.
`scroll-behavior: smooth;`

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptic-pr03** [comment]
If the issue is valid, could you please assign me?

**Comment by himanshu-03** [comment]
> If the issue is valid, could you please assign me?

Hello @cryptic-pr03 !
I have assinged you this issue. Let us know if  you need any help from our side.
