### ISSUE TITLE
add tnp site low fidelity diagram

### ISSUE THREAD

**Issue by demonkillerr** [tcet-opensource/documentation#3]

**Comment by vish-rt** [comment]
Use Miro or any other software to construct low fidelity diagram of the contents below and push to your branch.



![Image](https://user-images.githubusercontent.com/93420999/227581175-53ab82cf-bb5f-413e-8487-ec435ff7affb.jpg)
![Image](https://user-images.githubusercontent.com/93420999/227581174-5c858e65-850d-487a-a536-8edec39fc20f.jpg)
![Image](https://user-images.githubusercontent.com/93420999/227581177-8b21d955-3ef8-4724-8c9f-568596dd8174.jpg)
![Image](https://user-images.githubusercontent.com/93420999/227581176-9ef0ed5f-fd73-4723-98d6-2dd3aebfef8b.jpg)
![Image](https://user-images.githubusercontent.com/93420999/227581178-3b50b21c-3787-4861-826a-7b94e21b8ce2.jpg)
