### ISSUE TITLE
[TL] - yay-install

### ISSUE THREAD

**Issue by Akash6222** [tcet-opensource/documentation#308]
### Describe the improvement

This documentation will help you out to install yay on your system

### Why do we need this?

This will help new user to install yay 

### Do you have a proposed solution?

Bhai upar sab likh diya h ab kuch nhi baccha 

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by vish-rt** [comment]
Solved in #309
