### ISSUE TITLE
Document Docs website

### ISSUE THREAD

**Issue by vish-rt** [tcet-opensource/documentation#31]
Write about Docusaurus, the changes made in the navbar, sidebars, progress on the landing page, file structure, etc.

**Comment by himanshu-03** [comment]
Are we sure that we have to write about navbar too?

Navbar
- Logo Added
- Website Title Changed
- Docs and Blog Categories added


Anything else to cover in the navbar documentation?

**Comment by vish-rt** [comment]
I believe we will also add a search functionality soon if it's not added already. Would be great to highlight that as well!

**Comment by himanshu-03** [comment]
- [ ] About Docs
- [ ] Navbar
- [ ] Sidebar
- [ ] Progress on Landing Page

@vish-rt @demonkillerr  Do append other things that are to be done for documenting Docs Website

**Comment by himanshu-03** [comment]
All the documentations are completed as per expectations in Docs Site.
The home page for Open Source which is revamped will be documented after deployment!
