### ISSUE TITLE
[BUG] - Update Twitter icon to X

### ISSUE THREAD

**Issue by dalvishruti14** [tcet-opensource/documentation#319]
### Describe the bug

The Twitter logo in the footer is not updated.
![tcet](https://github.com/tcet-opensource/documentation/assets/120911455/37c1f103-8f10-418d-b039-bce06a337079)

### Expected behavior

It should be changed to X

### How to Reproduce?

Replace it with new logo 

### Screenshots

<img width="960" alt="twi" src="https://github.com/tcet-opensource/documentation/assets/120911455/caeccb4c-5bd9-4927-bbd1-854728aadb62">

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct
- Can I work on this issue?

**Comment by Soorya666** [comment]
hey @harshau007 can i take up this issue?

**Comment by MJ665** [comment]
https://github.com/tcet-opensource/documentation/pull/322

Issue Complited
