### ISSUE TITLE
[BUG] - Typo for "Announcement"

### ISSUE THREAD

**Issue by Soorya666** [tcet-opensource/documentation#320]
### Describe the bug

- There is a minor typo in the blogs section where the title was misspelled with a missing letter "n" in the route ``/docs/about-opensource``

### Actual behavior

- the appropriate spelling would be: Announcement 
## Image: 
![image](https://github.com/tcet-opensource/documentation/assets/130153710/6e8f44db-fd86-4f02-a00f-acb91ad6e062)

### Expected behavior

To appear as the correct word spelled "**ANNOUNCEMENT**"

### How to Reproduce?

Respell the word from ``"ANNOUCEMENT"`` TO ```"ANNOUNCEMENT"```

### Screenshots

![image](https://github.com/tcet-opensource/documentation/assets/130153710/8afb8155-53b3-4dce-98c3-e310be85e0f1)
- Image containing the typo of the title.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by MJ665** [comment]
the issue is done successfully

https://github.com/tcet-opensource/documentation/pull/321
