### ISSUE TITLE
[FIX] Installation In Drive

### ISSUE THREAD

**Issue by vish-rt** [tcet-opensource/documentation#333]
For better understanding of our documentation on TCET Linux, especially installation of the OS itself; nomenclature used should be appropriate.

You are required to rename `installation-in-drive.md` to `create-bootable-usb.md` to highlight what's covered in the page.

It's also important to rename all occurrences of `installation-in-drive` to `create-bootable-usb`. It needs to be done in three occurrences.
1. Line 3 of the same file (id)
2. Last line in `requirements-download-verify.md`
3. Route in `sidebars.js`

You also need to center all images present in the page itself.

**Comment by MJ665** [comment]
Done!
https://github.com/tcet-opensource/documentation/pull/340
