### ISSUE TITLE
[TL] edit Installation In VM Arch Linux additional steps

### ISSUE THREAD

**Issue by vish-rt** [tcet-opensource/documentation#334]
For better understanding of our documentation on TCET Linux, especially installation of the OS itself; steps and images used should be appropriate.

You are required to rename add screenshots in `installation-in-vm.md` to highlight Steps to Install TCET Linux on a Virtual Machine,

You also need to explain how to install VirtualBox to create and run Virtual Machines.

**Comment by MJ665** [comment]
https://github.com/tcet-opensource/documentation/pull/351

Done
