### ISSUE TITLE
[FEATURE] - Official Release

### ISSUE THREAD

**Issue by vish-rt** [tcet-opensource/documentation#336]
### Describe the improvement

Edit the file `variant-releases.md` or `releases.md` to highlight the Official Release of TCET Linux

### Why do we need this?

Because we are releasing TCET Linux

### Do you have a proposed solution?

To make sure documentation is up to snuff before the OS release is made

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by MJ665** [comment]
https://github.com/tcet-opensource/documentation/pull/341

Done !
