### ISSUE TITLE
[FEATURE] - Explain Partitioning

### ISSUE THREAD

**Issue by vish-rt** [tcet-opensource/documentation#337]
### Describe the improvement

Add `partitioning.md` in the Installation folder which explains how to partition your memory during installation of TCET Linux.

### Why do we need this?

Partitioning is important and the end users must know how to do it.

### Do you have a proposed solution?

Write the page

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by MJ665** [comment]
The PR Link was 

https://github.com/tcet-opensource/documentation/pull/339

**Comment by MJ665** [comment]
The PR was Done & Merged
