### ISSUE TITLE
[TL] - Explain Manual Partitioning for Dual Boot & VM in installation steps

### ISSUE THREAD

**Issue by vish-rt** [tcet-opensource/documentation#338]
### Describe the improvement

Explain Manual Partitioning for dual boot and VM in installation steps

### Why do we need this?

To explain and resolve confusion on partitioning on dual boot & VM install

### Do you have a proposed solution?

Explaining how to dual boot & VM in installation steps

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by MJ665** [comment]
Done
https://github.com/tcet-opensource/documentation/pull/343
