### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by vish-rt** [tcet-opensource/documentation#43]
## Add search bar to the open source website.

The documentation site will consist of several articles and pages for:
- Project installation
- Features
- Blog Posts
- Other articles as the website grows

This feature will be necessary for the documentation site because as the complexity grows, it would be difficult for a novice visitor to be able to browse through the navbars or sidebars to look for a specific feature.

**Comment by harshau007** [comment]
Is this issue assigned to anybody?

**Comment by himanshu-03** [comment]
Assigned to @harshau007

**Comment by himanshu-03** [comment]
- [ ] Fix Multiple Duplicate Search Terms Appearing in Search Bar

- [ ] Change the theme of the Search Bar in accordance with the theme of TCET Open Source

@harshau007 please take a note and do the changes accordingly.

**Comment by himanshu-03** [comment]
Hello @harshau007!
Would you like to work on this issue as you were previously assigned for this issue?
