### ISSUE TITLE
Create About Section for TCET Open Source Website

### ISSUE THREAD

**Issue by riyavishwa981** [tcet-opensource/documentation#47]
->Check [Figma](https://www.figma.com/file/csNMnd4hqC2cWhYL6GWNDD/Opensource-tcet?node-id=263-109&t=0ohSV2JsQUOBY79V-0) for correct fonts and colors
->Make your branch name as issue_number-about-section`
->It should be responsive

**Comment by JayeshVP24** [comment]
Highly suggesting you to read our changes and understand them.
