### ISSUE TITLE
Implement Search Bar

### ISSUE THREAD

**Issue by demonkillerr** [tcet-opensource/documentation#65]
Create a search bar that will allow users to search for docs

**Comment by harshau007** [comment]
Is this currently assigned to anyone ?

**Comment by demonkillerr** [comment]
No. Let us know if you would like to work on this :) @himanshu-03 has some idea of how to implement it. Kindly get in touch with him.

I am ok with implementing the algolia powered search bar or lunasearch, whatever does the job best.

**Comment by vish-rt** [comment]
Noticed two redundant issues. Please refer Issue #43 hereafter for implementing this.
