### ISSUE TITLE
document activity dekho

### ISSUE THREAD

**Issue by demonkillerr** [tcet-opensource/documentation#7]
Document [](https://https://activitydekho.com/)

1) Directory structure
2) APIs/API Calls

@JayeshVP24 @vish-rt you can add points if you want

**Comment by MJ665** [comment]
my name is meet jain form F.T. AI-ML branch TCET and i would like to work on this issue can you please assign me this issue

**Comment by vish-rt** [comment]
I have assigned the issue to you. Here's what you need to do:
- Fork the repository.
- In the project directory structure, open `/docs/projects/` and create a directory for ActivityDekho (refer directory structure of currently documented projects)
- You can get started with the **Directory structure** documentation for ActivityDekho. 
- Once done, send a pull request to `main`.

**Comment by JayeshVP24** [comment]
# Folder Structure
public -> All static files
src -> components -> All reusable and abstracted components are here
src -> firebase -> All firebase config is here and firebase queries are inside firestore folder inside here
src -> machines -> xstate Finite State Machines which hold all the logic exist here
src -> utils -> all utility functions are here
src -> pages -> all files here are a page

**Comment by MJ665** [comment]
i have corrected my previous pull request

I hope now this is corrcet
[new Activity-Dekho-DirectoryStructure.md](https://github.com/tcet-opensource/documentation/files/11337069/new.Activity-Dekho-DirectoryStructure.md)

**Comment by JayeshVP24** [comment]
you should push your changes

**Comment by himanshu-03** [comment]
Stale
