### ISSUE TITLE
Changes Required [BLOG] - #88

### ISSUE THREAD

**Issue by himanshu-03** [tcet-opensource/documentation#93]
Changes required in PR(#88) - @Nidhi-1223 

1. Use `##` or `###` instead of  `=== (MDX version of h1 tag)` while giving headings as it should be visible in Table of Contents in your blogs page.

   ![image](https://github.com/tcet-opensource/documentation/assets/97957777/8cea1b9c-c6f7-4c85-b5b4-f6183fc4534e)

2. Use `en dash (-)` instead of `em dash (—)` in the Title of the blog

   ![image](https://github.com/tcet-opensource/documentation/assets/97957777/6b2fe13e-387c-4a82-868a-7a156b39d716)

**Comment by Nidhi-1223** [comment]
Alright. We'll update soon

**Comment by Nidhi-1223** [comment]
Changes done in 7da9a6732a7ab015f8938fc24d4aea3316be971c

**Comment by himanshu-03** [comment]
Looks good 👍
